### ISSUE TITLE
apache2 port

### ISSUE THREAD

**Issue by CaptainSifff** [GeekOops/geekoops-nginx#4]
Hi all,
I have ported over your excellent nginx script over to apache2:
https://github.com/CaptainSifff/geekoops-apache
 In my environment it works on OpenSuse 15.4
maybe you want to include it in your selection?

**Comment by grisu48** [comment]
Closing the issue, feel free to reopen if you have any issues in moving the repository over. Welcome again.

**Comment by CaptainSifff** [comment]
Thanks for adding! I've moved the project over.
